import { test, expect } from '@playwright/test';

test('basic navigation', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.locator('#fmRegistro').getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('borrar@prueba.com');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('Hola1234*');
  await page.locator('#btnLogin').click();
  await page.getByRole('button', { name: 'Usuario' }).click();
  await page.getByRole('link', { name: 'Mi cuenta' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).fill('UnNombre2');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('heading', { name: 'UnNombre2' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).fill('UnNombre');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('heading', { name: 'UnNombre' }).click();
  await page.getByRole('button', { name: 'Volver' }).click();
  await page.getByRole('button', { name: 'Entrar' }).first().click();
  await page.getByRole('button', { name: 'Crear partida' }).click();
  await page.getByLabel('Modo').selectOption('PVBOT');
  await page.getByRole('button', { name: 'Crear', exact: true }).click();
  await page.getByRole('button', { name: 'Salir al lobby' }).click();
  await page.getByRole('button', { name: 'Entrar' }).nth(1).click();
  await page.getByRole('button', { name: 'Crear partida' }).click();
  await page.getByLabel('Modo').selectOption('PVBOT');
  await page.getByRole('button', { name: 'Crear', exact: true }).click();
  await page.getByRole('button', { name: 'Abandonar' }).click();
  await page.getByRole('button', { name: 'Entrar' }).nth(2).click();
  await page.getByRole('button', { name: 'Crear partida' }).click();
  await page.getByLabel('Modo').selectOption('PVBOT');
  await page.getByRole('button', { name: 'Crear', exact: true }).click();
  await page.getByRole('button', { name: 'Abandonar' }).click();
});